---
- hosts: localhost
  gather_facts: false
  vars:
    image: "flatcar"
    kubernetes_cluster_name: "test1"
    kubernetes_cluster_network: "mafiarpg-default"
    kubernetes_cluster_floating_ip_network: "provider"
    kubernetes_node_keypairs: []
    kubernetes_master_count: 1
    kubernetes_master_flavor_name: "m1.large"
    kubernetes_master_hosts: []
    kubernetes_node_count: 1
    kubernetes_node_flavor_name: "m1.medium"
    kubernetes_node_hosts: []
    os_config_file_path: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  tasks:
    - stat:
        path: "{{ os_config_file_path }}"
      register: os_config_file
    - include_vars: "{{ os_config_file_path }}"
      when: os_config_file.stat.exists and os_config_file.stat.isreg
    - name: Generate nodes keypair
      openstack.cloud.keypair:
        name: "{{ (kubernetes_cluster_name + '-keypair') }}"
        auth: "{{ clouds.devstack.auth }}"
      register: generated_keypair
    - name: Create nodes credential
      awx.awx.tower_credential:
        name: "{{ kubernetes_cluster_name + '-node-keypair' | to_uuid }}"
        description: "{{ kubernetes_cluster_name + 'Node SSH Credential' }}"
        organization: MafiaRPG
        kind: ssh
        inputs:
          username: core
          ssh_key_data: "{{ generated_keypair.key.private_key }}"
    - name: Generate list of keypairs
      set_fact:
        kubernetes_node_keypairs: "{{ kubernetes_node_keypairs + [item.public_key] }}"
      with_items:
        - "{{ generated_keypair.key }}"
        - "{{ ssh_keypair }}"
    - name: Create cluster inventory
      awx.awx.tower_inventory:
        name: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
        description: "{{ kubernetes_cluster_name + ' cluster inventory' }}"
    - name: Create OpenStack source
      awx.awx.tower_inventory_source:
        name: "{{ kubernetes_cluster_name + '-openstack' | to_uuid }}"
        description: "{{ kubernetes_cluster_name + ' cluster OpenStack inventory source' }}"
        inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
        source: openstack
        credential: MafiaRPG OpenStack
    - block:
        - name: Create master provision job template
          awx.awx.tower_job_template:
            name: "{{ kubernetes_cluster_name + '-master-deploy' | to_uuid }}"
            description: "{{ kubernetes_cluster_name + ' cluster master deploy job' }}"
            project: KubeSpray
            playbook: cluster.yml
            inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
            credentials:
              - "{{ kubernetes_cluster_name + '-node-keypair' | to_uuid }}"
            host_config_key: "{{ callback_key }}"
          register: job_template_reg
        - name: debug job template
          debug:
            msg: "Job template create result: {{ job_template_reg }}"
        - name: Generate Kubernetes node user-data
          set_fact:
            userdata: "{{ lookup('template', 'userdata/flatcar.j2') }}"
        - block:
          - name: Create Kubernetes master data volume
            openstack.cloud.volume:
              name: "{{ kubernetes_cluster_name + '-master' + item + '-volume' | to_uuid }}"
              description: "{{ kubernetes_cluster_name + ' cluster master' + item + ' data volume' }}"
              state: present
              auth: "{{ clouds.devstack.auth }}"
              size: "{{ kubernetes_master_volume_size | default('40') }}"
          - name: Create Kubernetes master instance
            openstack.cloud.server:
              name: "{{ kubernetes_cluster_name + '-kubernetes-master' + item }}"
              state: present
              auth: "{{ clouds.devstack.auth }}"
              flavor: "{{ kubernetes_master_flavor_name }}"
              image: "{{ image }}"
              network: "{{ kubernetes_cluster_network }}"
              floating_ip_pools:
                - "{{ kubernetes_cluster_floating_ip_network }}"
              security_groups:
                - default
                - Kubernetes Master
              volumes:
                - "{{ kubernetes_cluster_name + '-master' + item + '-volume' | to_uuid }}"
              userdata: "{{ userdata | to_json }}"
          with_sequence: start=1 end="{{ kubernetes_master_count + 1}}"
      vars:
        callback_key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
    - name: Provision Kubernetes nodes
      block:
        - name: Create Kubernetes node data volume
          openstack.cloud.volume:
            name: "{{ kubernetes_cluster_name + '-node' + item + '-volume' | to_uuid }}"
            description: "{{ kubernetes_cluster_name + ' cluster node' + item + ' data volume' }}"
            state: present
            auth: "{{ clouds.devstack.auth }}"
            size: "{{ kubernetes_node_volume_size | default('40') }}"
        - name: Create Kubernetes node instance
          openstack.cloud.server:
            name: "{{ kubernetes_cluster_name + '-kubernetes-node' + item }}"
            state: present
            auth: "{{ clouds.devstack.auth }}"
            flavor: "{{ kubernetes_worker_flavor_name }}"
            image: "{{ image }}"
            network: "{{ kubernetes_cluster_network }}"
            floating_ip_pools:
              - "{{ kubernetes_cluster_floating_ip_network }}"
            security_groups:
              - default
              - Kubernetes Node
            volumes:
              - "{{ kubernetes_cluster_name + '-node' + item + '-volume' | to_uuid }}"
            userdata: "{{ kubernetes_node_userdata | to_json }}"
        - name: Add instance to list
          set_fact:
            kubernetes_node_hosts: "{{ kubernetes_node_hosts + (kubernetes_cluster_name + '-kubernetes-node' + item) }}"
      with_sequence: start=1 end="{{ kubernetes_node_count + 1}}"
    - name: Update cluster inventory
      awx.awx.tower_invetory_source_update:
        name: "{{ kubernetes_cluster_name + '-openstack' | to_uuid }}"
        inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
    - name: Create host groups
      block:
        - name: Create masters group
          awx.awx.tower_group:
            name: kube-master
            inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
            hosts: "{{ kubernetes_master_hosts }}"
        - name: Create etcd group
          awx.awx.tower_group:
            name: etcd
            inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
            hosts: "{{ kubernetes_master_hosts }}"
        - name: Create nodes group
          awx.awx.tower_group:
            name: kube-node
            inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
            hosts: "{{ kubernetes_node_hosts }}"
        - name: Create masters group
          awx.awx.tower_group:
            name: calico-rr
            inventory: "{{ kubernetes_cluster_name + '-inventory' | to_uuid }}"
        - name: Create common group
          awx.awx.tower_group:
            name: k8s-cluster
            children:
              - kube-master
              - kube-node
              - calico-rr


